### ISSUE TITLE
How shoud we surprise Sasha??

### ISSUE THREAD

**Issue by MishkaSorochinskiy** [Galiv/bdayOfSasha#1]
Let's talk about gift and decide what he needs most of all))

![50-happy-birthday-quotes-thumb](https://user-images.githubusercontent.com/44136629/56091836-9fd66000-5ebc-11e9-9d0b-398d33a0d596.jpg)

**Comment by Galiv** [comment]
He said he needs new case for the phone... What do you think? @MishkaSorochinskiy

**Comment by MishkaSorochinskiy** [comment]
Not bad)) But i think It is too cheap )) It is better to give him new earpods)) He **deserves** smth special)
@Galiv

**Comment by Galiv** [comment]
Okay, your idea is better, let's do that, bro))
