### ISSUE TITLE
List of fun stuff 

### ISSUE THREAD

**Issue by Galiv** [Galiv/BdayOfSasha#6]
List of fun stuff we can do during the party

**Comment by Galiv** [comment]
What do you think we can do at the party? @MishkaSorochinskiy @maksat2992 @olegtsyb

**Comment by Galiv** [comment]
sorry, I meant @olegcyb

**Comment by MishkaSorochinskiy** [comment]
Maybe we can buy some  fireworks  and after that go to the party)) 

<img width="585" alt="fireworks-1170x878" src="https://user-images.githubusercontent.com/44136629/56092258-5721a580-5ec2-11e9-9e5c-b3edb32a6953.png">

**Comment by olegcyb** [comment]
We can buy popcorn and watch a movie

**Comment by Galiv** [comment]
Good idea, @olegcyb

**Comment by Galiv** [comment]
Okay, since no other ideas, let's watch the movies and after midnight we will do the fireworks

**Comment by maksat2992** [comment]
hello boys,we can go to night club "Malevich"

**Comment by maksat2992** [comment]
hello boys,we can go to night club "Malevich"
